version: '3.9'
services:
    db:
        image: postgres:15.0
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - /Users/valerijvorobev/gitother/postgres-compose/data:/var/lib/postgresql/data
            - /Users/valerijvorobev/gitother/postgres-compose/init.sh:/docker-entrypoint-initdb.d/init.sh
        ports:
            - 5432:5432